courseinfo/urls.py
from django.conf.urls import url
from courseinfo.views import InstructorList, InstructorDetail, InstructorCreate, InstructorUpdate, InstructorDelete, SectionList, SectionDetail, SectionCreate, SectionUpdate, SectionDelete, CourseList, CourseDetail, CourseCreate, CourseUpdate, CourseDelete, SemesterList, SemesterDetail, SemesterCreate, SemesterUpdate, SemesterDelete, StudentList, StudentDetail, StudentCreate, StudentUpdate, StudentDelete


urlpatterns = [
    url(r'^instructor/$',
        InstructorList.as_view(),
        name='courseinfo_instructor_list_urlpattern'
        ),
    url(r'instructor/(?P<requested_instructor_id>[\d]+)/$',
        InstructorDetail.as_view(),
        name='courseinfo_instructor_detail_urlpattern'),
    url(r'^instructor/create/$',
        InstructorCreate.as_view(),
        name='courseinfo_instructor_create_urlpattern'
        ),
    url(r'instructor/(?P<pk>[\d]+)/update/$',
        InstructorUpdate.as_view(),
        name='courseinfo_instructor_update_urlpattern'),
    url(r'instructor/(?P<requested_instructor_id>[\d]+)/delete/$',
        InstructorDelete.as_view(),
        name='courseinfo_instructor_delete_urlpattern'),
    url(r'^section/$',
        SectionList.as_view(),
        name='courseinfo_section_list_urlpattern'
        ),

    url(r'section/(?P<requested_section_id>[\d]+)/$',
        SectionDetail.as_view(),
        name='courseinfo_section_detail_urlpattern'),
    url(r'^section/create/$',
        SectionCreate.as_view(),
        name='courseinfo_section_create_urlpattern'
        ),
    url(r'section/(?P<pk>[\d]+)/update/$',
        SectionUpdate.as_view(),
        name='courseinfo_section_update_urlpattern'),
    url(r'section/(?P<pk>[\d]+)/delete/$',
        SectionDelete.as_view(),
        name='courseinfo_section_delete_urlpattern'),
    url(r'^course/$',
        CourseList.as_view(),
        name='courseinfo_course_list_urlpattern'
        ),
    url(r'course/(?P<requested_course_id>[\d]+)/$',
        CourseDetail.as_view(),
        name='courseinfo_course_detail_urlpattern'),
    url(r'^course/create/$',
        CourseCreate.as_view(),
        name='courseinfo_course_create_urlpattern'
        ),
    url(r'course/(?P<pk>[\d]+)/update/$',
        CourseUpdate.as_view(),
        name='courseinfo_course_update_urlpattern'),
    url(r'course/(?P<requested_course_id>[\d]+)/delete/$',
        CourseDelete.as_view(),
        name='courseinfo_course_delete_urlpattern'),
    url(r'^semester/$',
        SemesterList.as_view(),
        name='courseinfo_semester_list_urlpattern'
        ),
    url(r'semester/(?P<requested_semester_id>[\d]+)/$',
        SemesterDetail.as_view(),
        name='courseinfo_semester_detail_urlpattern'),
    url(r'^semester/create/$',
        SemesterCreate.as_view(),
        name='courseinfo_semester_create_urlpattern'
        ),
    url(r'semester/(?P<pk>[\d]+)/update/$',
        SemesterUpdate.as_view(),
        name='courseinfo_semester_update_urlpattern'),
    url(r'semester/(?P<requested_semester_id>[\d]+)/delete/$',
        SemesterDelete.as_view(),
        name='courseinfo_semester_delete_urlpattern'),
    url(r'^student/$',
        StudentList.as_view(),
        name='courseinfo_student_list_urlpattern'
        ),
    url(r'student/(?P<requested_student_id>[\d]+)/$',
        StudentDetail.as_view(),
        name='courseinfo_student_detail_urlpattern'),
    url(r'^student/create/$',
        StudentCreate.as_view(),
        name='courseinfo_student_create_urlpattern'
        ),
    url(r'student/(?P<pk>[\d]+)/update/$',
        StudentUpdate.as_view(),
        name='courseinfo_student_update_urlpattern'),
    url(r'student/(?P<requested_student_id>[\d]+)/delete/$',
        StudentDelete.as_view(),
        name='courseinfo_student_delete_urlpattern'),
]

ez_university/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import login
from django.views.generic import RedirectView, TemplateView

from courseinfo import urls as courseinfo_urls
from django.contrib.auth import views as auth_views




urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='about_urlpattern',
            permanent=False
        )),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='courseinfo/about.html'),
            name='about_urlpattern'
        ),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'courseinfo/login.html'},
        name='login_urlpattern'),
    url(r'^logout/$',
        auth_views.logout,
        {'next_page':'/login/'},
        name='logout_urlpattern'),

    url(r'^admin/', admin.site.urls),
    url(r'^', include(courseinfo_urls)),

]

courseinfo/models.py
from django.db import models
from django.core.urlresolvers import reverse


class CalendarPeriod(models.Model):
    calendar_period_id = models.IntegerField(primary_key=True)
    calendar_period_name = models.CharField(max_length=45,unique=True)

    def __str__(self):
        return '%s' % (self.calendar_period_name)

    class Meta:
        ordering = ['calendar_period_id']
        permissions = (
            ("view_calendarperiod", "Can view calendar period"),
        )


class Semester(models.Model):
    semester_id = models.AutoField(primary_key=True)
    # semester_name = models.CharField(max_length=45, unique=True)  deleted field
    year = models.IntegerField()    # added field
    calendar_period = models.ForeignKey(CalendarPeriod, related_name='semesters')  # added field

    def __str__(self):
        # return '%s' % (self.semester_name)   old version
        return '%s - %s' % (self.year, self.calendar_period.calendar_period_name)   # new version

    def get_absolute_url(self):
        return reverse('courseinfo_semester_detail_urlpattern',
                kwargs={'requested_semester_id': self.semester_id}
                )

    def get_update_url(self):
        return reverse('courseinfo_semester_update_urlpattern',
                       kwargs={'pk': self.semester_id}
        )

    def get_delete_url(self):
        return reverse(
            'courseinfo_semester_delete_urlpattern',
            kwargs={'requested_semester_id': self.semester_id}
        )

    class Meta:
        # ordering = ['semester_name']  old version
        ordering = ['year', 'calendar_period__calendar_period_id'] # revised version
        unique_together = ('year', 'calendar_period')  # added
        permissions = (
            ("view_semester", "Can view semester"),
        )



class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_number = models.CharField(max_length=20, unique=True)
    course_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % (self.course_number)

    def get_absolute_url(self):
        return reverse('courseinfo_course_detail_urlpattern',
                kwargs={'requested_course_id': self.course_id}
                )

    def get_update_url(self):
        return reverse('courseinfo_course_update_urlpattern',
                       kwargs={'pk': self.course_id}
        )

    def get_delete_url(self):
        return reverse(
            'courseinfo_course_delete_urlpattern',
            kwargs={'requested_course_id': self.course_id}
        )

    class Meta:
        ordering = ['course_number']
        permissions = (
            ("view_course", "Can view course"),
        )


class Instructor(models.Model):
    instructor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name )

    def get_absolute_url(self):
        return reverse('courseinfo_instructor_detail_urlpattern',
                kwargs={'requested_instructor_id': self.instructor_id}
                )

    def get_update_url(self):
        return reverse('courseinfo_instructor_update_urlpattern',
                       kwargs={'pk': self.instructor_id}
        )

    def get_delete_url(self):
        return reverse(
            'courseinfo_instructor_delete_urlpattern',
            kwargs={'requested_instructor_id': self.instructor_id}
        )

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (
            ("view_instructor", "Can view instructor"),
        )


class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    nickname = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.nickname == '':
            result = '%s, %s' % (self.last_name, self.first_name )
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.nickname )
        return result

    def get_absolute_url(self):
        return reverse('courseinfo_student_detail_urlpattern',
                kwargs={'requested_student_id': self.student_id}
                )

    def get_update_url(self):
        return reverse('courseinfo_student_update_urlpattern',
                       kwargs={'pk': self.student_id}
        )

    def get_delete_url(self):
        return reverse(
            'courseinfo_student_delete_urlpattern',
            kwargs={'requested_student_id': self.student_id}
        )

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (
            ("view_student", "Can view student"),
        )


class Section(models.Model):
    section_id = models.AutoField(primary_key=True)
    section_name = models.CharField(max_length=10)
    semester = models.ForeignKey(Semester, related_name='sections')
    course = models.ForeignKey(Course, related_name='sections')
    instructors = models.ManyToManyField(Instructor, related_name='sections')
    students = models.ManyToManyField(Student, related_name='sections')

    def __str__(self):
        # return '%s - %s (%s)' % (self.course.course_number, self.section_name, self.semester.semester_name)
        return '%s - %s (%s)' % (self.course.course_number, self.section_name, self.semester.__str__())

    def get_absolute_url(self):
        return reverse('courseinfo_section_detail_urlpattern',
                kwargs={'requested_section_id': self.section_id}
                )

    def get_update_url(self):
        return reverse('courseinfo_section_update_urlpattern',
                       kwargs={'pk': self.section_id}
        )

    def get_delete_url(self):
        return reverse(
            'courseinfo_section_delete_urlpattern',
            kwargs={'pk': self.section_id}
        )

    class Meta:
        # ordering = ['course__course_number', 'section_name', 'semester__semester_name']
        ordering = ['course__course_number', 'section_name', 'semester']
        permissions = (
            ("view_section", "Can view section"),
        )

courseinfo/forms.py
from django import forms

from courseinfo.models import Instructor, Section, Course, Semester, Student


class InstructorForm(forms.ModelForm):
    class Meta:
        model = Instructor
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = '__all__'

    def clean_section_name(self):
        return self.cleaned_data['section_name'].strip()


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

    def clean_course_name(self):
        return self.cleaned_data['course_name'].strip()

    def clean_course_number(self):
        return self.cleaned_data['course_number'].strip()


class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = '__all__'

    def clean_semester_name(self):
        return self.cleaned_data['semester_name'].strip()

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

courseinfo/templates/courseinfo/course_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Course
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{{ course.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Update Course</button>
    </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/course_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Course List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_course %}
    <a
        href="{% url 'courseinfo_course_create_urlpattern'  %}"
        class="button button-primary">
      Create New Course</a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h2>Course List</h2>
    {% if perms.courseinfo.add_course %}
    <div class="mobile">
      <a
          href="{% url 'courseinfo_course_create_urlpattern' %}"
          class="button button-primary">
        Create New Course</a>
    </div>
    {% endif %}
  <ul>
    {% for course in course_list %}
      <li>
        <a href="{{ course.get_absolute_url }}">
          {{ course }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no courses available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

courseinfo/templates/courseinfo/instructor_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Instructor
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ instructor.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          instructor {{ instructor }}?
        </p>
        <a
            href="{{ instructor.get_absolute_url }}"
            class="button button-primary">
          Cancel</a>
        <button type="submit">Delete Instructor</button>
      </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/instructor_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Instructor
{% endblock %}

{% block content %}
   <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{{ instructor.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Update Instructor</button>
    </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/instructor_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Instructor List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_instructor %}
    <a
        href="{% url 'courseinfo_instructor_create_urlpattern'  %}"
        class="button button-primary">
      Create New Instructor</a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h2>Instructor List</h2>
    {% if perms.courseinfo.add_instructor %}
    <div class="mobile">
      <a
          href="{% url 'courseinfo_instructor_create_urlpattern' %}"
          class="button button-primary">
        Create New Instructor</a>
    </div>
    {% endif %}
  <ul>
    {% for instructor in instructor_list %}
      <li>
        <a href="{{ instructor.get_absolute_url }}">
          {{ instructor }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no instructors available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

courseinfo/templates/courseinfo/section_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Section - {{ section }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ section }}</h2>
                <ul class="inline">
                    {% if perms.courseinfo.change_section %}
                    <li>
                        <a href="{{ section.get_update_url }}"
                           class="button">
                            Edit Section</a></li>
                    {% endif %}
                    {% if perms.courseinfo.delete_section %}
                    <li>
                        <a href="{{ section.get_delete_url }}"
                           class="button">
                            Delete Section</a></li>
                    {% endif %}
                </ul>

                <section>
                    <h3>Section Name</h3>
                    <p>{{ section.section_name }}</p>

                    <h3>Semester</h3>
                    <a href="{{ semester.get_absolute_url }}">{{ semester }}</a>

                    <h3>Course</h3>
                    <a href="{{ course.get_absolute_url }}">{{ course }}</a>
                </section>

                <section>
                    <h3>Instructors</h3>
                    <ul>
                        {% for instructor in instructor_list %}
                            <li>
                                <a href="{{ instructor.get_absolute_url }}">{{ instructor }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no instructors for this section.</em></li>
                        {% endfor %}
                    </ul>
                </section>
                <section>
                    <h3>Students</h3>
                    <ul>
                        {% for student in student_list %}
                            <li>
                                <a href="{{ student.get_absolute_url }}">{{ student }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no students registered for this section.</em></li>
                        {% endfor %}
                    </ul>
                </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

courseinfo/templates/courseinfo/section_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Section
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{% url 'courseinfo_section_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Create Section</button>
    </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/section_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Section
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{{ section.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Update Section</button>
    </form>
     </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/semester_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Semester
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ semester.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          semester {{ semester }}?
        </p>
        <a
            href="{{ semester.get_absolute_url }}"
            class="button button-primary">
          Cancel</a>
        <button type="submit">Delete Semester</button>
      </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/semester_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Semester
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{% url 'courseinfo_semester_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Create Semester</button>
    </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/semester_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Semester
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{{ semester.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="button-primary"
                type="submit">
                Update Semester</button>
    </form>
   </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/student_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Student
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ student.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          student {{ student }}?
        </p>
        <a
            href="{{ student.get_absolute_url }}"
            class="button button-primary">
          Cancel</a>
        <button type="submit">Delete Student</button>
      </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/student_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Student
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <form
        action="{{ student.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Student</button>
    </form>
    </div>
  </div>
{% endblock %}

courseinfo/templates/courseinfo/student_refuse_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Error Deleting Student
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
        <h2>Error Deleting Student</h2>
        <p>
            You may not delete student {{ student }}.  This
            student is currently enrolled in the following
            sections:
        </p>

        <ul>
            {% for section in sections %}
            <li><a href="{{ section.get_absolute_url }}">{{ section }}</a></li>
            {%  endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'courseinfo_student_list_urlpattern' %}">Student List</a>.
        </p>
    </div>
  </div>
{% endblock %}